# api
# serializer
COOKING_TIME_MIN = 1
AMOUNT_INGREDIENT = 1

# recipe
# models
TAG_SLUG_NAME_MAX_LENGTH = 32
INGREDIENT_NAME = 128
INGREDIENT_MASUREMENT_UNIT = 64
RECIPE_NAME_MAX_LENGTH = 256
SHORT_LINK_ID_LENGTH = 6
SHORT_LINK_URL_FIELD = 128

# users
# models
USER_NAME_LENGTH = 150
EMAIL_LENGTH = 254

# validators
DONT_USE_IN_USERNAME = 'me'
